blogproject/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^search/', views.search, name='search'),
]

blogproject/blogproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'', include('wechat.urls'))
]

blogproject/comments/urls.py
#!/usr/bin/env python3
# encoding: utf-8

"""
@version: ??
@author: Haoshi YU
@license: None
@file: url.py
@time: 2017/4/22 14:08
"""

from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blogproject/blog/models.py
# coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    """
        django 要求我们必须继承 models.Model 类，
        Category 只需要一个简单的分类名 name 就可以了。

        CharField 指定了 name 的数据类型，
        CharField 是字符型，
        max_length 指定其最大长度，
        超过这个长度的分类名就不能被存入数据库。

        当然 django 还为我们提供了各种各样的类型，
        如日期时间类型 DateTimeField、
        整数类型 IntegerField 等等。
        django 内置的类型全部类型可查看文档：
        https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    # 文章标题
    title = models.CharField(max_length=100)
    # 文章内容
    content = models.TextField()
    # 文章创建时间
    created_time = models.DateTimeField()
    # 文章最后修改时间
    modified_time = models.DateTimeField()
    # 文章摘要，可以没有文章摘要，
    # 但默认情况下 CharField 要求我们必须存入数据，
    # 否则就会报错。
    # 指定 blank=True 后就可以允许空值了。
    excerpt = models.TextField(max_length=200, blank=True)

    # 这是分类与标签，
    # 分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类与标签对应的表关联起来，
    # 但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，
    # 但是一个分类下可以有很多篇文章，
    # 所以我们使用的是 ForeignKey，
    # 即一对多的关系。
    # 而对于标签来说，
    # 一篇文章可以有多个标签，
    # 同一个标签下也可能有多篇文章，
    # 所以我们使用 ManyToManyField，
    # 表明这是多对多的关系。
    # 同时我们规定文章可以没有标签，
    # 因此为标签 tags 指定了 blank=True。
    # 请看教程中的解释，
    # 亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者
    # 这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，
    # 专门用于处理网站用户的注册、登录等流程，
    # User 是 django 为我们已经写好的用户模型，
    # 这里我们通过 ForeignKey 把文章和 User 关联起来，
    # 因为我们规定一篇文章只能有一个作者，
    # 而一个作者可能会写多篇文章，
    # 因此这是一对多的关系，
    # 和 Category 类似。
    author = models.ForeignKey(User)

    # 阅读数量
    views_num = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    # 自定get_absolute_url方法
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

    def increase_views_num(self):
        self.views_num += 1
        self.save(update_fields=['views_num'])

    # def save(self, *args, **kwargs):
    #     self.excerpt = self.content[:45]
    #     super(Post, self).save(*args, **kwargs)

# 完成后输入命令 python manage.py makemigrations
# 再输入 python manage.py migrate

blogproject/blog/views.py
# coding:utf-8
import markdown
from markdown.extensions.toc import TocExtension

from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView

# from comments.forms import CommentForm
from .models import Post, Category


# 首页视图函数
def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    paginator = Paginator(post_list, 10)
    page = request.GET.get('page')

    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)

    return render(request, 'blog/index.html', context={'post_list': post_list})


# # 详情页视图函数
# def detail(request, pk):
#
#     post = get_object_or_404(Post, pk=pk)
#     post.increase_views_num()
#     md = markdown.Markdown(extensions=[
#         'markdown.extensions.extra',
#         'markdown.extensions.codehilite',
#         TocExtension(slugify=slugify),
#     ])
#     post.content = md.convert(post.content)
#     return render(request, 'blog/detail.html', {'post': post, 'toc': md.toc})


# 记得在顶部导入 DetailView
class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):

        response = super(PostDetailView, self).get(request, *args, **kwargs)

        self.object.increase_views_num()

        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        #post.body = md.convert(post.body)
        post.content = md.convert(post.content)
        post.toc = md.toc
        return post










# 搜索功能
def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(title__icontains=q)
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'post_list': post_list})

    # 归档页（时间）
class ArchivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                                    created_time__month=month
                                                                )

# 分类页

class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)
















# # 归档页（时间）
# def archives(request, year, month):
#     post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
#     return render(request, 'blog/index.html', context={'post_list': post_list})
#
#
# # 分类页
# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate)
#     return render(request, 'blog/index.html', context={'post_list': post_list})

blogproject/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }} </a></span>
                <span class="post-date">
                    <a href="#">
                    <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                    </a>
                </span>
                <span class="post-author"><a href="#">{{ post.author }} </a></span>
                <span class="post-author"><a href="#">{{ post.views_num }} Reads</a></span>
                <!--<span class="comments-link"><a href="#">4 Comments</a></span>-->
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.content|safe }}
        </div>
    </article>
    <!--<section class="comment-area">
        <h2>留下你的评论</h2>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">Name:</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">Email:</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL:</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">Comments:</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit"><span>发表</span></button>
                </div>
            </div> 
        </form>
        <div class="comment-list">
            <h2>评论列表</h2>
            <ul class="list-unstyled">
                {% for comment in comment_list %}
                    <li>
                    <br>
                        <span class="comment-item">{{ comment.name }}</span>&nbsp;&nbsp;&nbsp;&nbsp;
                        <time class="date">{{ comment.created_time }}</time>

                        <div class="text">
                            <br>
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>-->
    <section class="comment-area">
        <!--PC和WAP自适应版-->
        <div id="SOHUCS" ></div>
        <script type="text/javascript">
            (function(){
                var appid = 'cysYJeFaP';
                var conf = 'prod_2a373ac9a86beb2a3b2fb1b7f05ff6c4';
                var width = window.innerWidth || document.documentElement.clientWidth;
                if (width < 960) {
                    window.document.write('<script id="changyan_mobile_js" charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/mobile/wap-js/changyan_mobile.js?client_id=' + appid + '&conf=' + conf + '"><\/script>');
                } else {
                    var loadJs = function (d, a) {
                        var c = document.getElementsByTagName("head")[0] || document.head || document.documentElement;
                        var b = document.createElement("script");
                        b.setAttribute("type", "text/javascript");
                        b.setAttribute("charset", "UTF-8");
                        b.setAttribute("src", d);
                        if (typeof a === "function") {
                            if (window.attachEvent) {
                                b.onreadystatechange = function () {
                                    var e = b.readyState;
                                    if (e === "loaded" || e === "complete") {
                                        b.onreadystatechange = null;
                                        a()
                                    }
                                }
                            } else {
                                b.onload = a
                            }
                        }
                        c.appendChild(b)
                    };
                    loadJs("https://changyan.sohu.com/upload/changyan.js", function () {
                        window.changyan.api.config({appid: appid, conf: conf})
                    });
                }
            })(); </script>

    </section>
{% endblock main %}
</aside>
{% block toc %}
  <div class="widget widget-content">
      <h3 class="widget-title">Article directory</h3>
      {{ post.toc|safe }}
  </div>
{% endblock toc %}

blogproject/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}

    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">

                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>

                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }} </a></span>
                    <span class="post-date">
                        <a href="#">
                            <time class="entry-date" datetime="{{ post.created_time }}">
                                {{ post.created_time }}
                            </time>
                        </a>
                    </span>
                    <span class="post-author"><a href="#">{{ post.author }} </a></span>

                    <!--<span class="comments-link"><a href="#">4 Comments</a></span>-->
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span
                            class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    <div class="page" style="text-align: center;margin-top: 50px">
        <ul class="pagination">
            {% if post_list.has_previous %}
                <li class="paginate_button previous">
                    <a href="?page={{ post_list.previous_page_number }}">上一页</a>
                </li>
            {% endif %}

            <li class="paginate_button disabled">
                <a href="#">第 {{ post_list.number }} 页 / 共 {{ post_list.paginator.num_pages }} 页</a>
            </li>
            {% if post_list.has_next %}
                <li class="paginate_button next">
                    <a href="?page={{ post_list.next_page_number }}">下一页</a>
                </li>
            {% endif %}
        </ul>
    </div>



{% endblock main %}